In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [9]:
X = np.array([[100,1], [200,2],[300,1],[400,3],[500,2],[600,3],[700,5],[800,6],[900,7],[1000,8]])
y = np.array([0,0,0,0,0,1,1,1,1,1])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8, 2)
(2, 2)
(8,)
(2,)


In [12]:
print(X_train)

[[ 600    3]
 [ 100    1]
 [ 800    6]
 [ 300    1]
 [1000    8]
 [ 500    2]
 [ 400    3]
 [ 700    5]]


In [13]:
print(X_test)

[[900   7]
 [200   2]]


In [14]:
print(y_train)

[1 0 1 0 1 0 0 1]


In [15]:
print(y_test)

[1 0]


In [16]:
model = LogisticRegression()

In [17]:
model.fit(X,y)

LogisticRegression()

In [20]:
model.predict(X_train)

array([1, 0, 1, 0, 1, 0, 0, 1])

In [21]:
import pandas as pd

data = pd.DataFrame(model.predict(X_train), columns=['predictions'])
data

predictions
0            1
1            0
2            1
3            0
4            1
5            0
6            0
7            1

In [23]:
y_pred = model.predict(X_test)

print("Length of y_test: ",len(y_test))
print("Length of y_pred: ",len(y_pred))

Length of y_test:  2
Length of y_pred:  2


In [24]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ",accuracy)

Accuracy:  1.0


In [25]:
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix: \n",conf_matrix)

Confusion Matrix: 
 [[1 0]
 [0 1]]
