In [ ]:
import torch
from torch.autograd import Variable

x_data = Variable(torch.Tensor([[1.0], [2.0], [3.0]]))
y_data = Variable(torch.Tensor([[2.0], [4.0], [6.0]]))

print(x_data)
print(y_data)

tensor([[1.],
        [2.],
        [3.]])
tensor([[2.],
        [4.],
        [6.]])


In [ ]:
class LinearRegressionModel(torch.nn.Module):

    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.linear = torch.nn.Linear(1, 1)  # One in and one out

    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred




## Linear Regression

y = mx+b

x is the independent variable <br>
y is the dependent variable <br>
m is the slope of line <br>
b is the intercept <br>

In [ ]:
import torch
import torch.nn as nn
import numpy as np

# Create some toy data
x_train = torch.randn(100, 1)  # 100 data points, each with 1 feature
y_train = 2 * x_train + 1 + 0.1 * torch.randn(100, 1)  # Noisy linear relationship

print(x_train)
print(y_train)

tensor([[-0.6622],
        [-0.9552],
        [-0.5136],
        [-2.0353],
        [ 1.6911],
        [ 0.2139],
        [-2.0371],
        [-0.2526],
        [ 0.0400],
        [ 1.2344],
        [-1.3538],
        [ 0.6812],
        [ 1.5110],
        [-0.9491],
        [-0.8771],
        [-0.9010],
        [-0.9378],
        [-1.0684],
        [-0.4660],
        [-0.4302],
        [ 0.4217],
        [-0.6551],
        [-0.0337],
        [ 0.2337],
        [ 0.7091],
        [-0.8472],
        [-1.4812],
        [-1.1302],
        [ 1.3974],
        [-0.9236],
        [-0.1244],
        [ 0.2460],
        [-1.2526],
        [ 0.6526],
        [ 1.4454],
        [ 0.6393],
        [-1.8561],
        [-0.1459],
        [-1.5648],
        [-0.2199],
        [-0.2147],
        [ 1.4598],
        [-0.6187],
        [ 0.9012],
        [-0.6379],
        [-0.5535],
        [-1.2999],
        [ 1.0137],
        [-0.0707],
        [-0.6622],
        [ 1.7159],
        [-1.8561],
        [-0.

In [ ]:


class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(input_size,output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

model = LinearRegression(1, 1)  # Input and output size are both 1

In [ ]:
model

LinearRegression(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [ ]:
# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
# Training loop
num_epochs = 100
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(x_train)
    loss = criterion(outputs, y_train)

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')


Epoch [10/100], Loss: 3.3182
Epoch [20/100], Loss: 2.1697
Epoch [30/100], Loss: 1.4287
Epoch [40/100], Loss: 0.9477
Epoch [50/100], Loss: 0.6338
Epoch [60/100], Loss: 0.4276
Epoch [70/100], Loss: 0.2913
Epoch [80/100], Loss: 0.2007
Epoch [90/100], Loss: 0.1402
Epoch [100/100], Loss: 0.0994


In [ ]:
# Make predictions
predicted = model(x_train).detach().numpy()
predicted

array([[-2.6039404e-01],
       [-7.6623255e-01],
       [-3.8075447e-03],
       [-2.6308742e+00],
       [ 3.8024468e+00],
       [ 1.2521135e+00],
       [-2.6340525e+00],
       [ 4.4685498e-01],
       [ 9.5195580e-01],
       [ 3.0140378e+00],
       [-1.4543319e+00],
       [ 2.0589311e+00],
       [ 3.4915388e+00],
       [-7.5568300e-01],
       [-6.3136226e-01],
       [-6.7266911e-01],
       [-7.3614532e-01],
       [-9.6166629e-01],
       [ 7.8451335e-02],
       [ 1.4016461e-01],
       [ 1.6109285e+00],
       [-2.4803275e-01],
       [ 8.2472414e-01],
       [ 1.2863649e+00],
       [ 2.1070633e+00],
       [-5.7966703e-01],
       [-1.6743793e+00],
       [-1.0682726e+00],
       [ 3.2954283e+00],
       [-7.1165532e-01],
       [ 6.6813225e-01],
       [ 1.3075908e+00],
       [-1.2796760e+00],
       [ 2.0095437e+00],
       [ 3.3783417e+00],
       [ 1.9866211e+00],
       [-2.3214841e+00],
       [ 6.3094741e-01],
       [-1.8186300e+00],
       [ 5.0331128e-01],
